### ISSUE TITLE
Add more SQLite error checking code

### ISSUE THREAD

**Issue by mpentler** [mpentler/pastebin-mirror#1]
Right now there’s a single error check when accessing the database file for the first time in the app. This catches things like database locking errors or being unable to create the file and exits cleanly. However, later issues on database writing - such as disk I/O errors for things like no disk space available - aren’t caught and will produce a nasty exception.

We need to consider:

1. Should we add error checking on most/all of the accesses?
2. What do we want to do if data can’t be written? If the database is inaccessible it seems fine to exit(1). But do we want to abort execution the first time data can’t be written, or do we want to do something else?

**Comment by mpentler** [comment]
Any thoughts, @brannondorsey ?

**Comment by mpentler** [comment]
Also: should I be exiting the program and raising exceptions inside the scraper and storage modules, or just inside __main__.py ? Is there a best practise for this? I’m also unsure on exit vs sys.exit and whether I should use one over the other.

**Comment by brannondorsey** [comment]
Hey, thanks for taking this on :)

> 1. Should we add error checking on most/all of the accesses?

I'd say yes, within reason. Some of the errors will be edge cases and difficult to reproduce, however I'm in favor of errors with descriptive information. That is, as long as error checking doesn't come to represent half the code base, haha ;)

> 2. What do we want to do if data can’t be written...

I'd say its fine to exit as soon as there are write errors. If this is the case, something is definitely wrong, which could lead to undefined behavior if it continues. 

re: where should the errors live, I would prefer to have them in `main.py`. That is, if they are errors that convey something meaningful to the user. The reason I like to keep my message errors in the main file is that it allows someone looking at the code base to more easily understand what API calls can trigger what kinds of actions (without burying that information deep in other files). 

It looks like `sys.exit(...)` is preferred to `exit()` as described [here](https://stackoverflow.com/questions/6501121/difference-between-exit-and-sys-exit-in-python).

**Comment by mpentler** [comment]
Righto. I’ll try and make the functions return an error to main instead and do it all in there instead.

**Comment by mpentler** [comment]
Annoyingly it seems you can’t really read much from SQLite I/O errors to split them out. Just trap the main exception and print what happened.

**Comment by mpentler** [comment]
And I’ve succeeded with this now. Will bundle with other fixes into a single PR.

I love how you can put your exception check anywhere and it gets fed back from the module that failed. Another cool thing learnt!

**Comment by mpentler** [comment]
Turns out github doesn’t understand the word “partially”...

**Comment by mpentler** [comment]
PR submitted for this one now. It’s not a full closing of the issue, but moves the checks into main.

I think just checks on the calls in the while loop now, then it can probably be closed.

**Comment by mpentler** [comment]
I've finished this issue now on my local repo. Just needs pushing
