### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by mpentler** [mpentler/pastebin-mirror#3]
There’s probably a need for a bit of intro text on load, as well as a bit of information while the code is running about what process is being carried out. 

Maybe it could be on a verbose option or something?

Maybe also print stats every so often or on every update on what’s happening so far? This session/total across all sessions?

This is all in order of priority so I’ll do it in that order.

**Comment by mpentler** [comment]
Much success on this @brannondorsey !

- added -q option to enable quiet mode, suppressing paste IDs only at the moment but can be used to suppress anything else we want. No suppressing of fatal errors, I would guess.
- added a stats display for total pastes and trending pastes downloaded for the current session.
- added some basic welcome text on load

**Comment by brannondorsey** [comment]
Great to hear! Shoot me a PR (from a feature branch if you want to keep developing on master) and I'll review and merge.

**Comment by mpentler** [comment]
I’ll be totally honest, I’m not a coder by trade so the workflow isn’t always second nature to me. I’m going direct to my fork’s master branch right now. 

I should have done it in a feature, merged the feature branch with my master, then done my PR, right

**Comment by brannondorsey** [comment]
No problem. This isn't too much of an issue at all if its just the two of us devin' anyway. But, it can definitely be a good practice to use a feature branch workflow when it comes to PRs. Not just for your contributer's sake, but also for your own sanity ;) The reason being that branches that PRs don't come from specific commits, but rather entire branches. Meaning, if you make a PR that sits there for a month+ waiting to be reviewed, any other changes you make to a branch over the course of that month get implicitly included on that original PR. 

For that reason, its nice to have more granular control over what commits get included in a PR, hence, feature branches. Does that make sense?

> I should have done it in a feature, merged the feature branch with my master, then done my PR, right

Not exactly, you keep the PR coming from a separate branch, but you make the request to my origin master? Then once it gets pulled, you pull my origin master into your origin master. Make sense?

Like I said, doesn't matter at all here, I'll take it however you send it. But its worth learning that ^ method for the future :+1:

**Comment by mpentler** [comment]
That does make sense I think :)

I’ll get my repo up to a standard with as many of these fixes and whatnot that we’ve already spoken about and then get it submitted.

Sent from my iPhone

On 3 Jan 2018, at 21:58, Brannon Dorsey <notifications@github.com<mailto:notifications@github.com>> wrote:


No problem. This isn't too much of an issue at all if its just the two of us devin' anyway. But, it can definitely be a good practice to use a feature branch workflow when it comes to PRs. Not just for your contributer's sake, but also for your own sanity ;) The reason being that branches that PRs don't come from specific commits, but rather entire branches. Meaning, if you make a PR that sits there for a month+ waiting to be reviewed, any other changes you make to a branch over the course of that month get implicitly included on that original PR.

For that reason, its nice to have more granular control over what commits get included in a PR, hence, feature branches. Does that make sense?

I should have done it in a feature, merged the feature branch with my master, then done my PR, right

Not exactly, you keep the PR coming from a separate branch, but you make the request to my origin master? Then once it gets pulled, you pull my origin master into your origin master. Make sense?

Like I said, doesn't matter at all here, I'll take it however you send it. But its worth learning that ^ method for the future 👍

**Comment by mpentler** [comment]
All displayed text in main.py that isn't an app-quitting fatal error has a --quiet check now. Just need to go through scraper.py...

**Comment by mpentler** [comment]
I’m going to close this as I’ll implement quiet mode for scraping routines under another issue. Current repo reflects changes done up to now.
